config/routes.rb
Rails.application.routes.draw do
  get 'blogs/new', to: 'blogs#new'

  post 'blogs/create', to: 'blogs#create'

  post 'blogs/confirm', to: 'blogs#confirm'

  get 'blogs/:id/edit', to: 'blogs#edit'

  patch 'blogs/:id/update', to: 'blogs#update'

  get 'blogs', to: 'blogs#index'

  delete 'blogs/:id/destroy', to: 'blogs#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, length: { in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  
  before_action :set_blog, only: [ :edit, :update, :destroy]
  
  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.save
    redirect_to blogs_path, notice: 'ブログを作成しました！'
  end

  def confirm
    @blog = Blog.new(blog_params)
    render :new if @blog.invalid?
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: 'ブログを更新しました！'
    else
      render 'edit'
    end
  end

  def index
    @blogs = Blog.all
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: 'ブログを削除しました！'
  end
  
  
  private
  
  def blog_params
    params.require( :blog).permit( :title, :content)
  end
  
  def set_blog
    @blog = Blog.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_path_new_or_edit
    if action_name == 'new'
      blogs_confirm_path
    elsif action_name == 'edit'
      "/blogs/#{@blog[:id]}/update"
    end
  end
end

app/views/blogs/_form.html.erb
<% if @blog.errors.any? %>
  <h3><%= @blog.errors.count %>件のエラーがあります！</h3>
  <ul>
    <% @blog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with(model: @blog, local: true, url: choose_path_new_or_edit) do |form| %>
  <h4><%= form.label :'タイトル' %></h4>
  <div class = 'blog_title'>
    <%= form.text_field :title, size: "30" %>
  </div>
  <h4><%= form.label :'本文' %></h4>
  <div class = 'blog_content'>
    <%= form.text_area :content, size: "70*2" %>
  </div>
  <br>
  <%= form.submit %>

<% end %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で投稿しますか？</h3>

<%= form_with(model: @blog, local: true, url: blogs_create_path) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  
  <h4>タイトル</h4>
  <div class = "confirm_blog_title">
    <p><%= @blog.title %></p>
  </div>
  <h4>本文</h4>
  <div class = "confirm_blog_content">
    <p><%= @blog.content %></p>
  </div>
  <div class = "button_to_create">
    <%= form.submit '投稿する' %>
  </div>
  
<% end %>

<br>

<%= form_with(model: @blog, local: true, url: blogs_new_path, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <div class ="button_back_to_new">
    <%= form.submit '戻る', name: 'back' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h2>ブログの編集</h2>

<%= render 'form' %>

app/views/blogs/index.html.erb
<h2>ブログ一覧</h2>
<h3><%= notice %></h3>

<table>
  <tr>
    <th>タイトル</th>
    <th>本文</th>
    <th>作成日時</th>
    <th>最終更新日時</th>
  </tr>
  
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog[:title] %></td>
      <td><%= blog[:content] %></td>
      <td><%= blog[:created_at] %></td>
      <td><%= blog[:updated_at] %></td>
      <td><%= link_to 'ブログを編集する', "/blogs/#{blog[:id]}/edit" %></td>
      <td><%= link_to 'ブログを削除する', "/blogs/#{blog[:id]}/destroy", method: 'delete' %></td>
    </tr>
  <% end %>
  
</table>

<br>
<%= link_to 'ブログを新規作成する', blogs_new_path %>

app/views/blogs/new.html.erb
<h2>ブログの新規作成</h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsNyumonExam2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>